"""Second-order ExPen solver for orthogonality-constrained problems on the Stiefel manifold.

This module implements a **second-order (inexact) Newton–Krylov method** for minimizing the
"exponential-penalty" objective (ExPen) introduced by Xiao & Liu (2022):

    min_{X \in R^{n\times p}}  h(X) := f( X(\tfrac32 I_p - \tfrac12 X^\top X) )
                               + \tfrac\beta4 \|X^\top X - I_p\|_F^2.

It is intended to be structurally similar to the provided `second_order_landing.py`:
- explicit gradient and Hessian-vector product (HVP)
- a Krylov linear solver (GMRES) for the Newton equation
- an inexact forcing rule (Eisenstat–Walker style) for the inner solve
- simple globalization via Armijo backtracking

You provide the original objective oracles:
    cost_f(X) -> scalar
    grad_f(X) -> (n,p) array
    hess_f(X, V) -> (n,p) array  (Hessian action / HVP of f at X applied to V)

References (formulas):
- Proposition 2.8 (gradient of h)
- Proposition 2.9 (HVP / Hessian action of h)

Dependencies:
    numpy, scipy (scipy.sparse.linalg.gmres, LinearOperator)

Author: generated by ChatGPT for the user's project.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable, Dict, Optional, Tuple

import time
import numpy as np

from PenCS import tangent_residual_val

from linear_solvers import euc_metric_minres

try:
    from scipy.sparse.linalg import LinearOperator, minres, cg
except Exception as e:  # pragma: no cover
    raise ImportError("expen_second_order.py requires scipy (gmres, LinearOperator).") from e

Array = np.ndarray


def sym(A: Array) -> Array:
    """Symmetrization operator Φ(A) = (A + A^T)/2."""
    return 0.5 * (A + A.T)


def expen_map_A(XTX: Array) -> Array:
    """A(X) := (3/2) I - (1/2) X^T X."""
    p = XTX.shape[0]
    return 1.5 * np.eye(p) - 0.5 * XTX


def expen_Y(X: Array) -> Tuple[Array, Array, Array]:
    """Return (Y, XTX, A) where Y = X A and A = 3/2 I - 1/2 X^T X."""
    XTX = X.T @ X
    A = expen_map_A(XTX)
    Y = X @ A
    return Y, XTX, A


def JX_action(X: Array, D: Array, *, XTX: Optional[Array] = None, A: Optional[Array] = None) -> Array:
    """Jacobian action J_X(D) of the mapping X \mapsto X(3/2 I - 1/2 X^T X).

    J_X(D) = D(3/2 I - 1/2 X^T X) - X Φ(X^T D).
    """
    if XTX is None:
        XTX = X.T @ X
    if A is None:
        A = expen_map_A(XTX)
    return D @ A - X @ sym(X.T @ D)


@dataclass
class ExPenNewtonResult:
    X: Array
    iterations: int
    stopping_reason: str
    log: Dict[str, list]


class ExPenSecondOrderNewton:
    """Inexact Newton–Krylov method for ExPen.

    Parameters
    ----------
    beta : float
        Penalty parameter β.
    tol : float
        Stopping tolerance on ||∇h(X)||_F.
    max_iter : int
        Maximum outer iterations.
    linear_rtol : float | None
        Fixed relative residual tolerance for GMRES. If None, uses forcing rule:
            rtol_k = min(zeta_max, ||∇h(X_k)||_F^theta).
    theta : float
        Forcing exponent θ > 0.
    zeta_max : float
        Upper bound on the forcing term.
    linear_maxiter : int
        Max GMRES iterations.
    damping : float
        Initial Levenberg–Marquardt damping μ for solving (H + μI)s = -g.
    ls_c1 : float
        Armijo parameter.
    ls_rho : float
        Backtracking contraction factor in (0,1).
    ls_max_steps : int
        Max backtracking steps.
    verbosity : int
        0 silent; >=1 prints per-iteration summary.

    Notes
    -----
    - This is a Euclidean Newton method on the unconstrained ExPen objective.
    - If the computed Newton direction is not a descent direction, damping is increased.
    """

    def __init__(
        self,
        *,
        beta: float = 1e2,
        tol: float = 1e-8,
        atol: Optional[float] = None,
        max_iter: int = 200,
        linear_rtol: Optional[float] = None,
        theta: float = 1.0,
        zeta_max: float = 1e-2,
        linear_maxiter: int = 200,
        damping: float = 1e-6,
        ls_c1: float = 1e-4,
        ls_rho: float = 0.5,
        ls_max_steps: int = 25,
        verbosity: int = 1,
    ):
        if beta <= 0:
            raise ValueError("beta must be positive")
        if tol <= 0:
            raise ValueError("tol must be positive")
        if max_iter <= 0:
            raise ValueError("max_iter must be positive")
        if linear_rtol is not None and not (0 < linear_rtol < 1):
            raise ValueError("linear_rtol must be in (0,1)")
        if theta <= 0:
            raise ValueError("theta must be positive")
        if not (0 < zeta_max < 1):
            raise ValueError("zeta_max must be in (0,1)")
        if damping < 0:
            raise ValueError("damping must be nonnegative")
        if not (0 < ls_c1 < 1):
            raise ValueError("ls_c1 must be in (0,1)")
        if not (0 < ls_rho < 1):
            raise ValueError("ls_rho must be in (0,1)")

        self.beta = float(beta)
        self.tol = float(tol)
        self.atol = None if atol is None else float(atol)
        self.max_iter = int(max_iter)
        self.linear_rtol = linear_rtol
        self.theta = float(theta)
        self.zeta_max = float(zeta_max)
        self.linear_maxiter = int(linear_maxiter)
        self.damping0 = float(damping)
        self.ls_c1 = float(ls_c1)
        self.ls_rho = float(ls_rho)
        self.ls_max_steps = int(ls_max_steps)
        self.verbosity = int(verbosity)

    # ---------- ExPen objective + oracles (gradient + HVP) ----------

    def cost_h(self, X: Array, cost_f: Callable[[Array], float]) -> float:
        Y, XTX, _A = expen_Y(X)
        pen = 0.25 * self.beta * float(np.linalg.norm(XTX - np.eye(XTX.shape[0]), ord="fro") ** 2)
        return float(cost_f(Y)) + pen

    def grad_h(self, X: Array, grad_f: Callable[[Array], Array]) -> Tuple[Array, Dict[str, Array]]:
        """Return (∇h(X), cache) where cache contains Y, XTX, A, G=∇f(Y)."""
        Y, XTX, A = expen_Y(X)
        G = grad_f(Y)
        p = XTX.shape[0]
        I = np.eye(p)

        # ∇h(X) = G A - X Φ(X^T G) + β X (X^T X - I)
        grad = G @ A - X @ sym(X.T @ G) + self.beta * X @ (XTX - I)

        cache = {"Y": Y, "XTX": XTX, "A": A, "G": G}
        return grad, cache

    def T1(self, X: Array, grad_f: Callable[[Array], Array]) -> Array:
        """Relative gradient T1(X) = 2*skew(∇f(X) X^T) X.

        Algebraically: ∇f(X)(X^T X) - X(∇f(X)^T X).
        """
        G = grad_f(X)
        return G @ (X.T @ X) - X @ (G.T @ X)

    def hvp_h(
        self,
        X: Array,
        D: Array,
        *,
        grad_f: Callable[[Array], Array],
        hess_f: Callable[[Array, Array], Array],
        cache: Optional[Dict[str, Array]] = None,
    ) -> Array:
        """Hessian action ∇^2 h(X)[D] using Prop. 2.9.

        Requires the original Hessian action H(Y)[·] = ∇^2 f(Y)[·].
        """
        if cache is None:
            Y, XTX, A = expen_Y(X)
            G = grad_f(Y)
        else:
            Y = cache["Y"]
            XTX = cache["XTX"]
            A = cache["A"]
            G = cache["G"]

        p = XTX.shape[0]
        I = np.eye(p)

        # JX(D)
        JXD = JX_action(X, D, XTX=XTX, A=A)

        # H-part: JX( H(Y)[ JX(D) ] )
        HJ = hess_f(Y, JXD)
        term1 = JX_action(X, HJ, XTX=XTX, A=A)

        # - D Φ(X^T G) - X Φ(D^T G) - G Φ(D^T X)
        term2 = -D @ sym(X.T @ G)
        term3 = -X @ sym(D.T @ G)
        term4 = -G @ sym(D.T @ X)
        hvp_g = term1 + term2 + term3 + term4

        # penalty Hessian: β(2XΦ(X^T D) + D(X^T X - I))
        hvp_pen = self.beta * (2.0 * X @ sym(X.T @ D) + D @ (XTX - I))

        return hvp_g + hvp_pen

    # ---------- Outer algorithm ----------

    def run(
        self,
        *,
        n: int,
        p: int,
        cost_f: Callable[[Array], float],
        grad_f: Callable[[Array], Array],
        hess_f: Callable[[Array, Array], Array],
        X0: Optional[Array] = None,
        seed: Optional[int] = None,
        callback: Optional[Callable[[Array, int], Any]] = None,
    ) -> ExPenNewtonResult:
        rng = np.random.default_rng(seed)
        if X0 is None:
            X = rng.standard_normal((n, p))
        else:
            X = np.array(X0, dtype=float, copy=True)

        log: Dict[str, list] = {
            "time": [],
            "cost": [],
            "tangent_residual": [],
            "ortho_error": [],
            "step_size": [],
            "linear_info": [],
            "linear_relres": [],
            "damping": [],
        }

        t_start = time.perf_counter()
        stopping_reason = "max_iter"

        # Callback contract (per-iterate):
        #   callback(X, iteration) -> Any
        # The callback is called once per iteration with the current iterate X.
        # If the callback returns True or the string "stop", the optimizer terminates early.
        #
        # Example:
        #   def cb(X, k):
        #       dist = subspace_distance(X, X_ref)
        #       history.append(dist)
        #       return False

        mu = self.damping0

        for k in range(1, self.max_iter + 1):
            h_val = self.cost_h(X, cost_f)
            grad, cache = self.grad_h(X, grad_f)
            g = grad
            g_norm = float(np.linalg.norm(g, ord="fro"))
            ortho = float(np.linalg.norm(cache["XTX"] - np.eye(p), ord="fro"))

            f_val = cost_f(X)

            relative_tangent=self.T1(X, grad_f)
            tangent_residual= np.linalg.norm(relative_tangent, ord="fro")

            elapsed = float(time.perf_counter() - t_start)
            log["time"].append(elapsed)
            log["cost"].append(f_val)
            # log["tangent_residual"].append(g_norm)
            log["tangent_residual"].append(tangent_residual)
            log["ortho_error"].append(ortho)

            if self.verbosity >= 1:
                print(
                    f"[ExPen-Newton {k:4d}] t={elapsed:8.3f}s  h={h_val:.6e}  ||∇h||={g_norm:.3e}  ||X^T X-I||={ortho:.3e}  μ={mu:.1e}"
                )

            # Per-iteration callback hook (only expose current iterate X)
            if callable(callback):
                try:
                    cb_ret = callback(X, k)
                except Exception as ex:
                    raise RuntimeError(f"Callback raised an exception at iteration {k}: {ex}") from ex
                if cb_ret is True or cb_ret == "stop":
                    stopping_reason = "callback"
                    break

            if g_norm <= self.tol:
                stopping_reason = "tol"
                break

            # --- inexact forcing (relative residual tolerance for GMRES) ---
            if self.linear_rtol is None:
                rtol = float(min(self.zeta_max, g_norm ** self.theta))
            else:
                rtol = float(self.linear_rtol)

            # --- define linear operator (H + μI) ---
            # nvar = n * p

            # def matvec(v: Array) -> Array:
            #     D = v.reshape(n, p)
            #     HD = self.hvp_h(X, D, grad_f=grad_f, hess_f=hess_f, cache=cache)
            #     if mu > 0:
            #         HD = HD + mu * D
            #     return HD.reshape(nvar)

            # Aop = LinearOperator((nvar, nvar), matvec=matvec, dtype=float)

            # b = (-g).reshape(nvar)

            # # Solve with minres
            # s_vec, info = euc_metric_minres(Aop, b, rtol=rtol, maxiter=self.linear_maxiter)
            # print(rtol)
            # print(info)
            # s = s_vec.reshape(n, p)

            def Hessop(V: Array) -> Array:
                HessV = self.hvp_h(X, V, grad_f=grad_f, hess_f=hess_f, cache=cache)
                return HessV

            b = -g

            # Solve with minres
            s, info = euc_metric_minres(Hessop, b, rtol=rtol, maxiter=self.linear_maxiter)
            print(rtol)



            #new
            X = X +  s

            # # Solve with MINRES
            # s_vec, info = minres(Aop, b, rtol=rtol, maxiter=self.linear_maxiter)
            # s = s_vec.reshape(n, p)

            # # estimated relative residual
            # r = b - Aop.matvec(s_vec)
            # relres = float(np.linalg.norm(r) / max(np.linalg.norm(b), 1e-32))
            # log["linear_info"].append(int(info))
            # log["linear_relres"].append(relres)

            # # Descent check for the penalized objective h:
            # # directional derivative = <grad h(X), s>
            # gTs = float(np.tensordot(g, s, axes=([0, 1], [0, 1])))

            # # If s is not a descent direction, increase damping and re-solve a few times
            # if (not np.isfinite(gTs)) or gTs >= 0.0:
            #     success = False
            #     for _ in range(5):
            #         mu = max(1e-12, 10.0 * max(mu, 1e-12))

            #         def matvec2(v: Array) -> Array:
            #             D = v.reshape(n, p)
            #             HD = self.hvp_h(X, D, grad_f=grad_f, hess_f=hess_f, cache=cache)
            #             HD = HD + mu * D
            #             return HD.reshape(nvar)

            #         Aop2 = LinearOperator((nvar, nvar), matvec=matvec2, dtype=float)
            #         s_vec, info = minres(Aop2, b, rtol=rtol, maxiter=self.linear_maxiter)
            #         s = s_vec.reshape(n, p)

            #         r = b - Aop2.matvec(s_vec)
            #         relres = float(np.linalg.norm(r) / max(np.linalg.norm(b), 1e-32))

            #         gTs = float(np.tensordot(g, s, axes=([0, 1], [0, 1])))
            #         if np.isfinite(gTs) and gTs < 0.0:
            #             success = True
            #             break

            #     # still not descent: fall back to steepest descent on h
            #     if not success:
            #         s = -g
            #         gTs = -float(np.linalg.norm(g, ord="fro") ** 2)

            # # Armijo backtracking on h
            # t = 1.0
            # h0 = h_val
            # accepted = False

            # for _ls in range(self.ls_max_steps):
            #     X_trial = X + t * s
            #     h_trial = self.cost_h(X_trial, cost_f)

            #     if np.isfinite(h_trial) and h_trial <= h0 + self.ls_c1 * t * gTs:
            #         accepted = True
            #         break

            #     t *= self.ls_rho

            # if not accepted:
            #     # line search failed: increase damping and take a very small step
            #     mu = max(1e-12, 10.0 * max(mu, 1e-12))
            #     t = min(t, 1e-3)

            # log["step_size"].append(float(t))
            # log["damping"].append(float(mu))

            # X = X + t * s

            # # mild damping update heuristic
            # if relres <= 0.1 * rtol:
            #     mu *= 0.2
            # elif relres > rtol:
            #     mu *= 2.0


        if log["time"]:
            t0 = log["time"][0]
            log["time"] = [t - t0 for t in log["time"]]

        return ExPenNewtonResult(
            X=X,
            iterations=len(log["cost"]),
            stopping_reason=stopping_reason,
            log=log,
        )


# -------------------- minimal example --------------------

def _example_brockett(seed: int = 0) -> None:  # pragma: no cover
    """Small Brockett example: f(X)=0.5 tr(X^T B X C), with symmetric B,C."""
    rng = np.random.default_rng(seed)
    n, p = 200, 20
    B = rng.standard_normal((n, n)); B = sym(B)
    C = rng.standard_normal((p, p)); C = sym(C)

    def cost_f(X: Array) -> float:
        return 0.5 * float(np.trace(X.T @ B @ X @ C))

    def grad_f(X: Array) -> Array:
        # ∇f = B X C
        return B @ X @ C

    def hess_f(X: Array, V: Array) -> Array:
        # Hessian action: B V C
        return B @ V @ C

    solver = ExPenSecondOrderNewton(beta=1e2, tol=1e-8, max_iter=100, verbosity=1)
    res = solver.run(n=n, p=p, cost_f=cost_f, grad_f=grad_f, hess_f=hess_f, seed=seed)
    print(res.stopping_reason, res.iterations)


if __name__ == "__main__":  # pragma: no cover
    _example_brockett()
